### ISSUE TITLE
The licenses may not be compatible

### ISSUE THREAD

**Issue by wycks** [WordPress/book#12]
I don't think GPLv2 is  compatible with Creative Commons Sharealike license.

As far as I know the only CC license that is GPL compatible is [CC0](http://wiki.creativecommons.org/CC0_FAQ)

From [Gnu GPL](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses):

> Creative Commons Attribution-Sharealike 2.0 license 
This is a copyleft free license that is good for artistic and entertainment works, and educational works. Please don't use it for software or documentation, since it is incompatible with the GNU GPL and with the GNU FDL.

My 2¢..license compatibility is pretty confusing considering.. it's a book on github which might be considered software.

**Comment by Otto42** [comment]
Old issue, but just a note to add that gnu.org now considers CC-BY 4.0 to be compatible, and the verdict on CC-BY-SA 4.0 is still being debated on the mailing lists.

**Comment by Otto42** [comment]
FYI, the public review and discussion on the CC mailing list has ended, and they'll likely be announcing BY-SA compatibility with the GPL or not sometime soon.

However, I noticed that the license on this GitHub is currently pointing to CC-BY-SA-3.0, instead of the latest 4.0 version. This should be upgraded to the 4.0 version, for maximum compatibility, and because if they do announce such, we would like it to be compatible with the GPLv3 immediately, regardless of the dual-licensing structure.
